---
Name: shortcodable
---
SilverStripe\Admin\LeftAndMain:
  extra_requirements_javascript:
    - 'restruct/silverstripe-shortcodable:client/dist/js/editor_plugin.js'
    - 'restruct/silverstripe-shortcodable:client/dist/js/shortcodable.js'
  extra_requirements_css:
    - 'restruct/silverstripe-shortcodable:client/dist/styles/shortcodable.css'

Shortcodable\Shortcodable:
  htmleditor_names:
    - cms

SilverStripe\Control\Director:
  rules:
    'admin/shortcodable': Shortcodable\Controllers\ShortcodableAdminController

SilverStripe\Forms\HTMLEditor\HTMLEditorField:
  extensions:
    - Shortcodable\Extensions\HtmlEditorFieldExtension

#Restruct\Silverstripe\AdminTweaks\Shortcodes\FeaturedImageShortcode:
#  extensions:
#    - Shortcodable\Extensions\ShortcodableTestExtension
#SilverStripe\Admin\LeftAndMain:
#  extensions:
#    - Silverstripe\Shortcodable\Extensions\LeftAndMainExtension
#
#Silverstripe\Shortcodable\ShortcodeParser:
#  extensions:
#    - Silverstripe\Shortcodable\ShortcodableShortcodeParserExtension
